# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e90afd1bdd85349c270dde818982679b7ac1010ee85426944fdff8de2d481cd1bbb1a66ba1216b80e7877c6a17f492b5cf13bff724dfa8be32bdda87c1dcaf5

test:
  secret_key_base: ee13e290b160b03e4f44334f6fcfb66a9b0ac4d2dc6f3a970b4187d3cbde6a0ae0354662d385aa116c47a3435de44a61c054545ca2d23e8fa1266c6d110d3457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
